In [ ]:
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

In [2]:
df = pd.read_csv(
    "/lustre/fsw/portfolios/llmservice/users/ninaxu/safe_synthesizer/cleaned/dow_jones_index_group_size_8.csv"
).head(15)

In [4]:

embedder = SentenceTransformer("distiluse-base-multilingual-cased-v2")


In [ ]:
# old method
def old_embed_text(df: pd.DataFrame, embedder) -> pd.DataFrame:
    """Takes a dataframe of text fields, finds the embeddings for each
    and then averages the embeddings into one embedding and returns a dataframe with just that
    """
    embeddings = {}
    # for col in df.columns:
    #     print(f"Embedding column: {col}")
    #     data = df[col].to_list()
    #     data = [str(r) for r in data]
    #     embeddings[col] = embedder.encode(data, show_progress_bar=False, convert_to_numpy=True)
    #     print(f"Embeddings for column {col}: {embeddings[col].shape}")

    for j in range(len(df.columns)):
        col = df.columns[j]
        embd = np.array([[0.1, 0.2, 0.3]] * 15) * j
        embeddings[col] = embd
        print(f"Embeddings for column {col}: {embd}")
    print("done embedding")

    avg_embeddings = []
    for i in range(3):
        # TODO: Is this average what we want? When there are more than 2 columns, we will
        # overweight later columns relative to earlier columns.
        norm = embeddings[df.columns[0]][i]
        for j in range(1, len(df.columns)):
            field = df.columns[j]
            norm = np.average([norm, embeddings[field][i]], axis=0)
            if i == 0:
                print(f"norm at j={j}: {norm}")

        avg_embeddings.append(norm)

    df_embeddings = pd.DataFrame({"embedding": list(avg_embeddings)})

    return df_embeddings

In [30]:
df_embeddings = old_embed_text(df, embedder)

Embeddings for column stock: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Embeddings for column date: [[0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]]
Embeddings for column open: [[0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]
 [0.2 0.4 0.6]]
Embeddings for column high: [[0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]
 [0.3 0.6 0.9]]
Embeddings for column low: [

In [32]:
def embed_text(df: pd.DataFrame, embedder) -> pd.DataFrame:
    """Takes a dataframe of text fields, finds the embeddings for each
    and then averages the embeddings into one embedding and returns a dataframe with just that
    """
    embeddings = {}
    # for col in df.columns:
    #     print(f"Embedding column: {col}")
    #     data = df[col].to_list()
    #     data = [str(r) for r in data]
    #     embeddings[col] = embedder.encode(data, show_progress_bar=False, convert_to_numpy=True)
    #     print(f"Embeddings for column {col}: {embeddings[col].shape}")

    for j in range(len(df.columns)):
        col = df.columns[j]
        embd = np.array([[0.1, 0.2, 0.3]] * 15) * j
        embeddings[col] = embd
        print(f"Embeddings for column {col}: {embd}")
    print("done embedding")

    stacked = np.stack([embeddings[col] for col in df.columns], axis=0)  # shape: (n_cols, n_rows, embed_dim)
    avg_embeddings = np.mean(stacked, axis=0)  # shape: (n_rows, embed_dim)

    return pd.DataFrame({"embedding": list(avg_embeddings)})
